'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.18063
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.18063。
'
Namespace GMGService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GMGServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GMGService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private View_MyCardCPSave_ScheduleCheckOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MyCardCPSave_CPTempData_InsertOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MyCardCPSave_Difference_ProcOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MyCardCPSave_ScheduleCheck_UpdateStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.GMGReport.My.MySettings.Default.GMGReport_GMGService_GMGService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event View_MyCardCPSave_ScheduleCheckCompleted As View_MyCardCPSave_ScheduleCheckCompletedEventHandler
        
        '''<remarks/>
        Public Event MyCardCPSave_CPTempData_InsertCompleted As MyCardCPSave_CPTempData_InsertCompletedEventHandler
        
        '''<remarks/>
        Public Event MyCardCPSave_Difference_ProcCompleted As MyCardCPSave_Difference_ProcCompletedEventHandler
        
        '''<remarks/>
        Public Event MyCardCPSave_ScheduleCheck_UpdateStatusCompleted As MyCardCPSave_ScheduleCheck_UpdateStatusCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/View_MyCardCPSave_ScheduleCheck", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function View_MyCardCPSave_ScheduleCheck(ByVal GameFacId As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("View_MyCardCPSave_ScheduleCheck", New Object() {GameFacId})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub View_MyCardCPSave_ScheduleCheckAsync(ByVal GameFacId As String)
            Me.View_MyCardCPSave_ScheduleCheckAsync(GameFacId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub View_MyCardCPSave_ScheduleCheckAsync(ByVal GameFacId As String, ByVal userState As Object)
            If (Me.View_MyCardCPSave_ScheduleCheckOperationCompleted Is Nothing) Then
                Me.View_MyCardCPSave_ScheduleCheckOperationCompleted = AddressOf Me.OnView_MyCardCPSave_ScheduleCheckOperationCompleted
            End If
            Me.InvokeAsync("View_MyCardCPSave_ScheduleCheck", New Object() {GameFacId}, Me.View_MyCardCPSave_ScheduleCheckOperationCompleted, userState)
        End Sub
        
        Private Sub OnView_MyCardCPSave_ScheduleCheckOperationCompleted(ByVal arg As Object)
            If (Not (Me.View_MyCardCPSave_ScheduleCheckCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent View_MyCardCPSave_ScheduleCheckCompleted(Me, New View_MyCardCPSave_ScheduleCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MyCardCPSave_CPTempData_Insert", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MyCardCPSave_CPTempData_Insert(ByVal PrcType As Integer, ByVal CP_TradeSeq As String, ByVal GameNo As String, ByVal ProductId As String, ByVal Item As String, ByVal Price As String, ByVal SaveDate As Date) As ReturnValue
            Dim results() As Object = Me.Invoke("MyCardCPSave_CPTempData_Insert", New Object() {PrcType, CP_TradeSeq, GameNo, ProductId, Item, Price, SaveDate})
            Return CType(results(0),ReturnValue)
        End Function
        
        '''<remarks/>
        Public Overloads Sub MyCardCPSave_CPTempData_InsertAsync(ByVal PrcType As Integer, ByVal CP_TradeSeq As String, ByVal GameNo As String, ByVal ProductId As String, ByVal Item As String, ByVal Price As String, ByVal SaveDate As Date)
            Me.MyCardCPSave_CPTempData_InsertAsync(PrcType, CP_TradeSeq, GameNo, ProductId, Item, Price, SaveDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MyCardCPSave_CPTempData_InsertAsync(ByVal PrcType As Integer, ByVal CP_TradeSeq As String, ByVal GameNo As String, ByVal ProductId As String, ByVal Item As String, ByVal Price As String, ByVal SaveDate As Date, ByVal userState As Object)
            If (Me.MyCardCPSave_CPTempData_InsertOperationCompleted Is Nothing) Then
                Me.MyCardCPSave_CPTempData_InsertOperationCompleted = AddressOf Me.OnMyCardCPSave_CPTempData_InsertOperationCompleted
            End If
            Me.InvokeAsync("MyCardCPSave_CPTempData_Insert", New Object() {PrcType, CP_TradeSeq, GameNo, ProductId, Item, Price, SaveDate}, Me.MyCardCPSave_CPTempData_InsertOperationCompleted, userState)
        End Sub
        
        Private Sub OnMyCardCPSave_CPTempData_InsertOperationCompleted(ByVal arg As Object)
            If (Not (Me.MyCardCPSave_CPTempData_InsertCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MyCardCPSave_CPTempData_InsertCompleted(Me, New MyCardCPSave_CPTempData_InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MyCardCPSave_Difference_Proc", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MyCardCPSave_Difference_Proc(ByVal GameFacId As String, ByVal GameSerId As String, ByVal SaveStartDate As Date, ByVal SaveEndDate As Date, ByVal CreateUser As String) As ReturnValue
            Dim results() As Object = Me.Invoke("MyCardCPSave_Difference_Proc", New Object() {GameFacId, GameSerId, SaveStartDate, SaveEndDate, CreateUser})
            Return CType(results(0),ReturnValue)
        End Function
        
        '''<remarks/>
        Public Overloads Sub MyCardCPSave_Difference_ProcAsync(ByVal GameFacId As String, ByVal GameSerId As String, ByVal SaveStartDate As Date, ByVal SaveEndDate As Date, ByVal CreateUser As String)
            Me.MyCardCPSave_Difference_ProcAsync(GameFacId, GameSerId, SaveStartDate, SaveEndDate, CreateUser, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MyCardCPSave_Difference_ProcAsync(ByVal GameFacId As String, ByVal GameSerId As String, ByVal SaveStartDate As Date, ByVal SaveEndDate As Date, ByVal CreateUser As String, ByVal userState As Object)
            If (Me.MyCardCPSave_Difference_ProcOperationCompleted Is Nothing) Then
                Me.MyCardCPSave_Difference_ProcOperationCompleted = AddressOf Me.OnMyCardCPSave_Difference_ProcOperationCompleted
            End If
            Me.InvokeAsync("MyCardCPSave_Difference_Proc", New Object() {GameFacId, GameSerId, SaveStartDate, SaveEndDate, CreateUser}, Me.MyCardCPSave_Difference_ProcOperationCompleted, userState)
        End Sub
        
        Private Sub OnMyCardCPSave_Difference_ProcOperationCompleted(ByVal arg As Object)
            If (Not (Me.MyCardCPSave_Difference_ProcCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MyCardCPSave_Difference_ProcCompleted(Me, New MyCardCPSave_Difference_ProcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MyCardCPSave_ScheduleCheck_UpdateStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MyCardCPSave_ScheduleCheck_UpdateStatus(ByVal Sn As Integer, ByVal Status As Integer, ByVal UserStamp As String) As ReturnValue
            Dim results() As Object = Me.Invoke("MyCardCPSave_ScheduleCheck_UpdateStatus", New Object() {Sn, Status, UserStamp})
            Return CType(results(0),ReturnValue)
        End Function
        
        '''<remarks/>
        Public Overloads Sub MyCardCPSave_ScheduleCheck_UpdateStatusAsync(ByVal Sn As Integer, ByVal Status As Integer, ByVal UserStamp As String)
            Me.MyCardCPSave_ScheduleCheck_UpdateStatusAsync(Sn, Status, UserStamp, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MyCardCPSave_ScheduleCheck_UpdateStatusAsync(ByVal Sn As Integer, ByVal Status As Integer, ByVal UserStamp As String, ByVal userState As Object)
            If (Me.MyCardCPSave_ScheduleCheck_UpdateStatusOperationCompleted Is Nothing) Then
                Me.MyCardCPSave_ScheduleCheck_UpdateStatusOperationCompleted = AddressOf Me.OnMyCardCPSave_ScheduleCheck_UpdateStatusOperationCompleted
            End If
            Me.InvokeAsync("MyCardCPSave_ScheduleCheck_UpdateStatus", New Object() {Sn, Status, UserStamp}, Me.MyCardCPSave_ScheduleCheck_UpdateStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnMyCardCPSave_ScheduleCheck_UpdateStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.MyCardCPSave_ScheduleCheck_UpdateStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MyCardCPSave_ScheduleCheck_UpdateStatusCompleted(Me, New MyCardCPSave_ScheduleCheck_UpdateStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ReturnValue
        
        Private returnMsgNoField As Integer
        
        Private returnMsgField As String
        
        Private returnDSField As System.Data.DataSet
        
        '''<remarks/>
        Public Property ReturnMsgNo() As Integer
            Get
                Return Me.returnMsgNoField
            End Get
            Set
                Me.returnMsgNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReturnMsg() As String
            Get
                Return Me.returnMsgField
            End Get
            Set
                Me.returnMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReturnDS() As System.Data.DataSet
            Get
                Return Me.returnDSField
            End Get
            Set
                Me.returnDSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub View_MyCardCPSave_ScheduleCheckCompletedEventHandler(ByVal sender As Object, ByVal e As View_MyCardCPSave_ScheduleCheckCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class View_MyCardCPSave_ScheduleCheckCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub MyCardCPSave_CPTempData_InsertCompletedEventHandler(ByVal sender As Object, ByVal e As MyCardCPSave_CPTempData_InsertCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class MyCardCPSave_CPTempData_InsertCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ReturnValue
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ReturnValue)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub MyCardCPSave_Difference_ProcCompletedEventHandler(ByVal sender As Object, ByVal e As MyCardCPSave_Difference_ProcCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class MyCardCPSave_Difference_ProcCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ReturnValue
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ReturnValue)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub MyCardCPSave_ScheduleCheck_UpdateStatusCompletedEventHandler(ByVal sender As Object, ByVal e As MyCardCPSave_ScheduleCheck_UpdateStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class MyCardCPSave_ScheduleCheck_UpdateStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ReturnValue
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ReturnValue)
            End Get
        End Property
    End Class
End Namespace
