//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormeplayAd.Service1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnValue", Namespace="http://schemas.datacontract.org/2004/07/WinFormeplayAdWcf")]
    [System.SerializableAttribute()]
    public partial class ReturnValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet ReturnDataSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnMsgNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet ReturnDataSet {
            get {
                return this.ReturnDataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDataSetField, value) != true)) {
                    this.ReturnDataSetField = value;
                    this.RaisePropertyChanged("ReturnDataSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnMsgNo {
            get {
                return this.ReturnMsgNoField;
            }
            set {
                if ((this.ReturnMsgNoField.Equals(value) != true)) {
                    this.ReturnMsgNoField = value;
                    this.RaisePropertyChanged("ReturnMsgNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/View_ADS_FilmInfo_UPLoadStatus", ReplyAction="http://tempuri.org/IService1/View_ADS_FilmInfo_UPLoadStatusResponse")]
        WinFormeplayAd.Service1.ReturnValue View_ADS_FilmInfo_UPLoadStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MyCard_ADS_FilmInfo_UPLoadStatus_UPDATE", ReplyAction="http://tempuri.org/IService1/MyCard_ADS_FilmInfo_UPLoadStatus_UPDATEResponse")]
        WinFormeplayAd.Service1.ReturnValue MyCard_ADS_FilmInfo_UPLoadStatus_UPDATE(int Sn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WinFormeplayAd.Service1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WinFormeplayAd.Service1.IService1>, WinFormeplayAd.Service1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinFormeplayAd.Service1.ReturnValue View_ADS_FilmInfo_UPLoadStatus() {
            return base.Channel.View_ADS_FilmInfo_UPLoadStatus();
        }
        
        public WinFormeplayAd.Service1.ReturnValue MyCard_ADS_FilmInfo_UPLoadStatus_UPDATE(int Sn) {
            return base.Channel.MyCard_ADS_FilmInfo_UPLoadStatus_UPDATE(Sn);
        }
    }
}
