//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18063
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCardPointsApi.ErrorLog_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="http://schemas.datacontract.org/2004/07/MyCardSystemErrorLog")]
    public enum ErrorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VIEW = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEB = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WINFORM = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="http://schemas.datacontract.org/2004/07/MyCardSystemErrorLog")]
    public enum FaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Web一般錯誤 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Web例外錯誤 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WS一般錯誤 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WS例外錯誤 = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyCardSystemErrorLogResult", Namespace="http://schemas.datacontract.org/2004/07/MyCardSystemErrorLog")]
    [System.SerializableAttribute()]
    public partial class MyCardSystemErrorLogResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnLogSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnErrorCode {
            get {
                return this.ReturnErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnErrorCodeField, value) != true)) {
                    this.ReturnErrorCodeField = value;
                    this.RaisePropertyChanged("ReturnErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnLogSn {
            get {
                return this.ReturnLogSnField;
            }
            set {
                if ((this.ReturnLogSnField.Equals(value) != true)) {
                    this.ReturnLogSnField = value;
                    this.RaisePropertyChanged("ReturnLogSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsgNo {
            get {
                return this.ReturnMsgNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgNoField, value) != true)) {
                    this.ReturnMsgNoField = value;
                    this.RaisePropertyChanged("ReturnMsgNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyCardSystemErrorLogQueryResult", Namespace="http://schemas.datacontract.org/2004/07/MyCardSystemErrorLog")]
    [System.SerializableAttribute()]
    public partial class MyCardSystemErrorLogQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnErrorCode {
            get {
                return this.ReturnErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnErrorCodeField, value) != true)) {
                    this.ReturnErrorCodeField = value;
                    this.RaisePropertyChanged("ReturnErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnErrorMsg {
            get {
                return this.ReturnErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnErrorMsgField, value) != true)) {
                    this.ReturnErrorMsgField = value;
                    this.RaisePropertyChanged("ReturnErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsgNo {
            get {
                return this.ReturnMsgNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgNoField, value) != true)) {
                    this.ReturnMsgNoField = value;
                    this.RaisePropertyChanged("ReturnMsgNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorLog_WS.ISystemErrorLogService")]
    public interface ISystemErrorLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemErrorLogService/MyCardSystemErrorLog", ReplyAction="http://tempuri.org/ISystemErrorLogService/MyCardSystemErrorLogResponse")]
        MyCardPointsApi.ErrorLog_WS.MyCardSystemErrorLogResult MyCardSystemErrorLog(string Project, string ErrorCode, MyCardPointsApi.ErrorLog_WS.ErrorType ErrorType, MyCardPointsApi.ErrorLog_WS.FaultType FaultType, string ObjectName, string KeyWord, string ErrorMsg, string TradeRecordValues, string ErrorIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemErrorLogService/MyCardSystemErrorLogQuery", ReplyAction="http://tempuri.org/ISystemErrorLogService/MyCardSystemErrorLogQueryResponse")]
        MyCardPointsApi.ErrorLog_WS.MyCardSystemErrorLogQueryResult MyCardSystemErrorLogQuery(string InErrorCode, string CrrnyShotName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemErrorLogServiceChannel : MyCardPointsApi.ErrorLog_WS.ISystemErrorLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemErrorLogServiceClient : System.ServiceModel.ClientBase<MyCardPointsApi.ErrorLog_WS.ISystemErrorLogService>, MyCardPointsApi.ErrorLog_WS.ISystemErrorLogService {
        
        public SystemErrorLogServiceClient() {
        }
        
        public SystemErrorLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemErrorLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemErrorLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemErrorLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyCardPointsApi.ErrorLog_WS.MyCardSystemErrorLogResult MyCardSystemErrorLog(string Project, string ErrorCode, MyCardPointsApi.ErrorLog_WS.ErrorType ErrorType, MyCardPointsApi.ErrorLog_WS.FaultType FaultType, string ObjectName, string KeyWord, string ErrorMsg, string TradeRecordValues, string ErrorIP) {
            return base.Channel.MyCardSystemErrorLog(Project, ErrorCode, ErrorType, FaultType, ObjectName, KeyWord, ErrorMsg, TradeRecordValues, ErrorIP);
        }
        
        public MyCardPointsApi.ErrorLog_WS.MyCardSystemErrorLogQueryResult MyCardSystemErrorLogQuery(string InErrorCode, string CrrnyShotName) {
            return base.Channel.MyCardSystemErrorLogQuery(InErrorCode, CrrnyShotName);
        }
    }
}
