//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18063
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCardPointsApi.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckMyCardForCardPoint", Namespace="http://schemas.datacontract.org/2004/07/MyCardPointsApiWcf")]
    [System.SerializableAttribute()]
    public partial class CheckMyCardForCardPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPrice {
            get {
                return this.CardPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPriceField, value) != true)) {
                    this.CardPriceField = value;
                    this.RaisePropertyChanged("CardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogSn {
            get {
                return this.LogSnField;
            }
            set {
                if ((object.ReferenceEquals(this.LogSnField, value) != true)) {
                    this.LogSnField = value;
                    this.RaisePropertyChanged("LogSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsgNo {
            get {
                return this.ReturnMsgNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgNoField, value) != true)) {
                    this.ReturnMsgNoField = value;
                    this.RaisePropertyChanged("ReturnMsgNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckMyCardForCardPoint", ReplyAction="http://tempuri.org/IService1/CheckMyCardForCardPointResponse")]
        MyCardPointsApi.ServiceReference1.CheckMyCardForCardPoint[] CheckMyCardForCardPoint(string MyCardNo, string GameServiceId, string GameServiceIp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MyCardPointsApi.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MyCardPointsApi.ServiceReference1.IService1>, MyCardPointsApi.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyCardPointsApi.ServiceReference1.CheckMyCardForCardPoint[] CheckMyCardForCardPoint(string MyCardNo, string GameServiceId, string GameServiceIp) {
            return base.Channel.CheckMyCardForCardPoint(MyCardNo, GameServiceId, GameServiceIp);
        }
    }
}
